### ISSUE TITLE
WHOKARYOTE step only uses 1 thread although setted THREADS="40"

### ISSUE THREAD

**Issue by shanexuuu** [mgabriell1/EUKsemble#5]
Hi, thanks for the amazing pipeline. However, the Whokaryote process is extremely slow for me (almost ~6 days and still "Using model with tiara predictions to predict contig class") and only using 1 thread, although I set  THREADS="40" in EUKsemble-CONFIG.conf and it did used 40 threads for the kaiju classification. The screenshot of what output I have and my setting of EUKsemble-CONFIG.conf are attached for your reference. I was wondering is there any advice for me? THX!

![screenshot](https://github.com/mgabriell1/EUKsemble/assets/113850758/68c955d8-3f83-4495-b4c5-84dcf68a2a98)
[workeg_EUKsemble-CONFIG.conf.txt](https://github.com/mgabriell1/EUKsemble/files/14977672/workeg_EUKsemble-CONFIG.conf.txt)

**Comment by mgabriell1** [comment]
Hi,
I'm glad you find the pipeline useful!
I've double checked whether I've missed something in the script, but indeed Whokaryote has no flags to handle multi-threading. It's been a while since I've done those tests but I also remember Tiara not being necessarily faster when using more threads..

 I think the quickest solution might be to just split the contigs that you have as input into multiple files (`seqkit split` might do the trick), run the different splits in parallel and then recombine all contigs of the same type into one. Given that each contig is evaluated by itself (there is no context within the metagenome) this trick will not change the overall output.
Since you have already completed the Kaiju step, I guess you can split also the output files (which in your case should be called 'kaiju.taxa.out' I think) according to the overall split to avoid re-running this step.

Let me know if this helps!
Cheers,

Marco

**Comment by shanexuuu** [comment]
> Hi, I'm glad you find the pipeline useful! I've double checked whether I've missed something in the script, but indeed Whokaryote has no flags to handle multi-threading. It's been a while since I've done those tests but I also remember Tiara not being necessarily faster when using more threads..
> 
> I think the quickest solution might be to just split the contigs that you have as input into multiple files (`seqkit split` might do the trick), run the different splits in parallel and then recombine all contigs of the same type into one. Given that each contig is evaluated by itself (there is no context within the metagenome) this trick will not change the overall output. Since you have already completed the Kaiju step, I guess you can split also the output files (which in your case should be called 'kaiju.taxa.out' I think) according to the overall split to avoid re-running this step.
> 
> Let me know if this helps! Cheers,
> 
> Marco
Hi Macro,

Yes it could work. I did split before Kaiju input (more convenient). Now all under DeepMicroClass (~66 threads per split and also this step takes long). Thanks!

**Comment by mgabriell1** [comment]
Great, happy to have helped!
